name: CI for FastAPI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 040783
          POSTGRES_DB: taskdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql+asyncpg://postgres:040783@localhost:5432/taskdb
      DATABASE_URL_LOCAL: postgresql+asyncpg://postgres:040783@localhost:5432/taskdb
      SECRET_KEY: testsecret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL to be ready
        run: |
          echo "Waiting for PostgreSQL to accept connections..."
          for i in {1..10}; do
            if pg_isready -h postgres -p 5432 && PGPASSWORD=040783 psql -h postgres -U postgres -d taskdb -c '\q'; then
              echo "PostgreSQL is ready!"
              break
            fi
            echo "Waiting ($i)..."
            sleep 3
          done

      - name: Run Alembic migrations
        run: alembic upgrade head
