name: CI for FastAPI Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 040783
          POSTGRES_DB: taskdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        volumes:
          - postgres-data:/var/lib/postgresql/data

    env:
      DATABASE_URL: postgresql+asyncpg://postgres:040783@postgres:5432/taskdb
      SYNC_DATABASE_URL: postgresql://postgres:040783@postgres:5432/taskdb
      SECRET_KEY: testsecret
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install psycopg2-binary

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for PostgreSQL..."
          for i in {1..15}; do
            if docker exec ${{ job.services.postgres.id }} pg_isready -U postgres; then
              echo "PostgreSQL is ready!"
              exit 0
            fi
            echo "Attempt $i: Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL failed to start"
          exit 1

      - name: Run Alembic migrations
        run: |
          # Verify alembic.ini exists and has correct content
          cat alembic.ini
          
          # Run migrations with debug output
          PYTHONPATH=. alembic -c alembic.ini upgrade head